name: Continuous Integration Checks

on: [ push, pull_request ]

jobs:
  build:
    strategy:
      matrix:
        toolchain: [ stable, beta, 1.75.0 ] # 1.75.0 is current MSRV for vss-client
        include:
          - toolchain: stable
            check-fmt: true
          - toolchain: 1.75.0
            msrv: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Install Protobuf compiler (protoc)
        run: sudo apt-get update && sudo apt-get -y install protobuf-compiler
      - name: Install Rust ${{ matrix.toolchain }} toolchain
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile=minimal --default-toolchain ${{ matrix.toolchain }}
          rustup override set ${{ matrix.toolchain }}
      - name: Pin packages to allow for MSRV
        if: matrix.msrv
        run: |
          cargo update -p idna_adapter --precise 1.1.0 # This has us use `unicode-normalization` which has a more conservative MSRV
          cargo update -p proptest --precise "1.8.0" --verbose # proptest 1.9.0 requires rustc 1.82.0
      - name: Build on Rust ${{ matrix.toolchain }}
        run: cargo build --verbose --color always
      - name: Check formatting
        if: matrix.check-fmt
        run: rustup component add rustfmt && cargo fmt --all -- --check
      - name: Test on Rust ${{ matrix.toolchain }}
        run: cargo test
      - name: Cargo check release on Rust ${{ matrix.toolchain }}
        run: cargo check --release
      - name: Cargo check doc on Rust ${{ matrix.toolchain }}
        run: cargo doc --release
